### ISSUE TITLE
Email links in your README

### ISSUE THREAD

**Issue by SinghCoder** [iamishansharma/iamishansharma#1]
Hey, just stumbled across this repo, and saw that in the emails (Gmail, BITS, and iCloud) you forgot to add a mailto: in front of those emails, and hence when someone opens them, it treats email as a relative URL to your repo url, which is not what you would have in mind.

To correct: change (xyz@abc.com)  to (mailto:xyz@abc.com), it should correct the issue.

PS: Liked the banner in your README

**Comment by iamishansharma** [comment]
OH DAMN, never noticed that it doesn't work. Changed now. Thanks a lot for suggesting!
